In [3]:
import json2vec as rf 
from relbench.datasets import get_dataset
dataset = get_dataset("rel-trial")

/Users/reid/py/benchmarks/.venv/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Downloading file 'rel-trial/db.zip' from 'https://relbench.stanford.edu/download/rel-trial/db.zip' to '/Users/reid/Library/Caches/relbench'.
100%|████████████████████████████████████████| 574M/574M [00:00<00:00, 413GB/s]
Unzipping contents of '/Users/reid/Library/Caches/relbench/rel-trial/db.zip' to '/Users/reid/Library/Caches/relbench/rel-trial/.'

In [13]:
db = dataset.get_db()

table_names = []

for table_name, table in db.table_dict.items():
    table_names.append(table_name)
    print(f"\n=== {table_name} ===")
    print(table.df.head())

=== outcomes ===
   id  nct_id outcome_type                                              title  \
0   0     332    Secondary  Mean Change From Baseline in Nighttime Symptom...
1   1     332    Secondary  Mean Change From Baseline in Rhinoconjunctivit...
2   2     332    Secondary  Mean Change From Baseline in Daytime Eye Sympt...
3   3     332    Secondary  Patient's Global Evaluation of Allergic Rhinit...
4   4     332    Secondary  Physician's Global Evaluation of Allergic Rhin...

                                         description           time_frame  \
0  Mean change from baseline in Nighttime Symptom...  Baseline and Week 2
1  Patients completed the validated, self-adminis...               Week 2
2  Mean change from baseline in Daytime Eye Sympt...  Baseline and Week 2
3  An evaluation by the patient, administered at ...               Week 2
4  An evaluation by the physician, administered a...               Week 2

                                          population             units  \
0  The secondary efficacy analyses were based on ...  Units on a Scale
1  This secondary endpoint analysis was performed...  Units on a Scale
2  The secondary efficacy analyses were based on ...  Units on a Scale
3  This secondary endpoint analysis was performed...  Units on a Scale
4  This secondary endpoint analysis was performed...  Units on a Scale

  units_analyzed          dispersion_type          param_type       date
0            NaN  95% Confidence Interval  Least Squares Mean 2000-05-31
1            NaN  95% Confidence Interval  Least Squares Mean 2000-05-31
2            NaN  95% Confidence Interval  Least Squares Mean 2000-05-31
3            NaN  95% Confidence Interval  Least Squares Mean 2000-05-31
4            NaN  95% Confidence Interval  Least Squares Mean 2000-05-31

=== interventions_studies ===
   id  nct_id  intervention_id       date
0   0      25             1619 2000-01-01
1   1      22              439 2000-01-01
2   2      15             1115 2000-01-01
3   3      17             2099 2000-01-01
4   4      15             1114 2000-01-01

=== drop_withdrawals ===
   id  nct_id         period            reason  count       date
0   0     332  Overall Study  Lack of Efficacy    8.0 2000-05-31
1   1     332  Overall Study      out-of-state    1.0 2000-05-31
2   2     332  Overall Study     Noncompliance    0.0 2000-05-31
3   3     332  Overall Study     Noncompliance    0.0 2000-05-31
4   4     332  Overall Study     Noncompliance    0.0 2000-05-31

=== sponsors ===
   sponsor_id                                    name agency_class
0           0   Johns Hopkins All Children's Hospital        OTHER
1           1            Florida Department of Health    OTHER_GOV
2           2                      NYU Langone Health        OTHER
3           3  Wake Forest University Health Sciences        OTHER
4           4                         Gilead Sciences     INDUSTRY

=== outcome_analyses ===
   id  nct_id  outcome_id            non_inferiority_type  \
0   0     646           7  Non-Inferiority or Equivalence
1   1     646           6  Non-Inferiority or Equivalence
2   2     757          12            Superiority or Other
3   3     757          10            Superiority or Other
4   4     757          11            Superiority or Other

                         non_inferiority_description         param_type  \
0  ANOVA will be performed on ln-transformed Ae0-...  Ratio of the mean
1  ANOVA will be performed on ln-transformed Ae0-...  Ratio of the mean
2                                                NaN                NaN
3                                                NaN                NaN
4                                                NaN                NaN

   param_value dispersion_type  dispersion_value p_value_modifier  ...  \
0        97.94             NaN               NaN              NaN  ...
1       100.36             NaN               NaN              NaN  ...
2          NaN             NaN               NaN                <  ...
3          NaN             NaN               NaN                <  ...
4          NaN             NaN               NaN                <  ...

   p_value_description           method  method_description  \
0                  NaN              NaN                 NaN
1                  NaN              NaN                 NaN
2                  NaN  t-test, 2 sided                 NaN
3                  NaN  t-test, 2 sided                 NaN
4                  NaN  t-test, 2 sided                 NaN

                                estimate_description  groups_description  \
0  Bioequivalence is established when 90% Confide...                 NaN
1  Bioequivalence is established when 90% Confide...                 NaN
2                                                NaN                 NaN
3                                                NaN                 NaN
4                                                NaN                 NaN

  other_analysis_description ci_upper_limit_raw ci_lower_limit_raw  \
0                        NaN                NaN                NaN
1                        NaN                NaN                NaN
2                        NaN                NaN                NaN
3                        NaN                NaN                NaN
4                        NaN                NaN                NaN

  p_value_raw       date
0         NaN 2000-07-31
1         NaN 2000-07-31
2         NaN 2000-09-30
3         NaN 2000-09-30
4         NaN 2000-09-30

[5 rows x 26 columns]

=== designs ===
   id  nct_id allocation intervention_model observational_model  \
0   0       5        NaN                NaN              Cohort
1   1       0        NaN                NaN              Cohort
2   2      10        NaN                NaN              Cohort
3   3      18        NaN                NaN              Cohort
4   4      11        NaN                NaN              Cohort

  primary_purpose time_perspective masking masking_description  \
0             NaN    Retrospective     NaN                 NaN
1             NaN    Retrospective     NaN                 NaN
2             NaN    Retrospective     NaN                 NaN
3             NaN    Retrospective     NaN                 NaN
4             NaN    Retrospective     NaN                 NaN

  intervention_model_description subject_masked caregiver_masked  \
0                            NaN            NaN              NaN
1                            NaN            NaN              NaN
2                            NaN            NaN              NaN
3                            NaN            NaN              NaN
4                            NaN            NaN              NaN

  investigator_masked outcomes_assessor_masked       date
0                 NaN                      NaN 2000-01-01
1                 NaN                      NaN 2000-01-01
2                 NaN                      NaN 2000-01-01
3                 NaN                      NaN 2000-01-01
4                 NaN                      NaN 2000-01-01

=== facilities_studies ===
   id  nct_id  facility_id       date
0   0      32       106096 2000-01-01
1   1      13       195100 2000-01-01
2   2       0         4376 2000-01-01
3   3      26       155494 2000-01-01
4   4       1        16788 2000-01-01

=== eligibilities ===
   id  nct_id         sampling_method gender minimum_age maximum_age  \
0   0       4  Non-Probability Sample    All         NaN         NaN
1   1       5  Non-Probability Sample    All    14 Years         NaN
2   2      15                     NaN    All    18 Years    90 Years
3   3      16  Non-Probability Sample    All         NaN         NaN
4   4       9      Probability Sample    All     2 Years    17 Years

  healthy_volunteers                                         population  \
0                 No  Patients with proven gastric adenocarcinoma un...
1                 No  914 Patients , who underwent surgical treatmen...
2                 No                                                NaN
3                 No  Patients with rectal adenocarcinoma who underw...
4                NaN  -included participants have had acute abdomina...

                                            criteria gender_description  \
0  Inclusion Criteria:~all patients undergoing su...                NaN
1  Inclusion Criteria:~age over 14 years old.~Pat...                NaN
2  Inclusion Criteria:~Patients with urothelial h...                NaN
3  Inclusion Criteria:~- all the patients who und...                NaN
4  Inclusion Criteria:~all children referred with...                NaN

  gender_based adult child older_adult       date
0          NaN     t     t           t 2000-01-01
1          NaN     t     t           t 2000-01-01
2          NaN     t     f           t 2000-01-01
3          NaN     t     t           t 2000-01-01
4          NaN     f     t           f 2000-01-01

=== conditions ===
   condition_id          mesh_term
0             0          Paralysis
1             1  Diabetes Mellitus
2             2             Myopia
3             3          Neoplasms
4             4             Anemia

=== sponsors_studies ===
   id  nct_id  sponsor_id lead_or_collaborator       date
0   0      10        5744                 lead 2000-01-01
1   1       0        2122                 lead 2000-01-01
2   2      14       11988                 lead 2000-01-01
3   3      26         887                 lead 2000-01-01
4   4       8       44556                 lead 2000-01-01

=== reported_event_totals ===
   id  nct_id event_type                 classification  subjects_affected  \
0   0     332      other    Total, other adverse events                0.0
1   1     332     deaths     Total, all-cause mortality                NaN
2   2     332    serious  Total, serious adverse events                0.0
3   3     332      other    Total, other adverse events                0.0
4   4     332     deaths     Total, all-cause mortality                NaN

   subjects_at_risk       date
0             352.0 2000-05-31
1               NaN 2000-05-31
2             348.0 2000-05-31
3             348.0 2000-05-31
4               NaN 2000-05-31

=== facilities ===
   facility_id                                     name           city  \
0            0                     Daiichi Sankyo, Inc.  Basking Ridge
1            1              Novartis Investigative Site  Yokohama-city
2            2  Fudan University Shanghai Cancer Center       Shanghai
3            3                  John Radcliffe Hospital         Oxford
4            4    University Clinic of Dentistry Vienna         Vienna

         state       zip         country
0   New Jersey     07920   United States
1     Kanagawa  231-0023           Japan
2     Shanghai    200032           China
3  Oxfordshire   OX3 9DU  United Kingdom
4          NaN      1090         Austria

=== studies ===
   nct_id start_date target_duration                        study_type  \
0       0 2000-01-01             NaN                     Observational
1       1 2000-01-01             NaN                     Observational
2       2 2000-01-01       60 Months  Observational [Patient Registry]
3       3 2000-01-01             NaN                     Observational
4       4 2000-01-01        17 Years  Observational [Patient Registry]

  acronym baseline_population  \
0  HEMAJA                 NaN
1     NaN                 NaN
2     NaN                 NaN
3     NaN                 NaN
4     NPS                 NaN

                                         brief_title  \
0  Unicentric Retrospective Analysis of a Cohort ...
1      The Major Bleeding Risk Following Hepatectomy
2        DLBCL Treatment in Children and Adolescents
3  Prognostic Factors Affecting Survival of Gastr...
4  Prognostic Performance of the Naples Prognosti...

                                      official_title phase  enrollment  ...  \
0  Unicentric Retrospective Analysis of a Cohort ...   NaN       602.0  ...
1  Evaluation of the Bleeding Risk Associated Wit...   NaN      5265.0  ...
2  Efficacy and Safety Comparison Between R-CHOP/...   NaN       106.0  ...
3  Clinicopathological Characteristics and Progno...   NaN        34.0  ...
4  The Naples Prognostic Score in Gastric Cancer ...   NaN       477.0  ...

  is_ppsd is_us_export  biospec_retention  biospec_description  source_class  \
0     NaN          NaN                NaN                  NaN         OTHER
1     NaN          NaN                NaN                  NaN         OTHER
2     NaN          NaN                NaN                  NaN         OTHER
3     NaN          NaN                NaN                  NaN         OTHER
4     NaN          NaN                NaN                  NaN         OTHER

  baseline_type_units_analyzed fdaaa801_violation plan_to_share_ipd  \
0                          NaN                NaN                No
1                          NaN                NaN                No
2                          NaN                NaN                No
3                          NaN                NaN         Undecided
4                          NaN                NaN               Yes

                               detailed_descriptions  \
0  The therapeutic results (response and survival...
1  The study population consisted of two cohorts....
2  Diffuse large B-cell lymphoma (DLBCL) is an ag...
3  The prognosis of gastric GIST depends on vario...
4  The outcome of oncological patients is related...

                                     brief_summaries
0  Unicentric retrospective analysis of a cohort ...
1  This study examined long-term incidence rates ...
2  We compared the efficacy and safety of modifie...
3  Gastrointestinal stromal tumor (GIST) is the m...
4  To investigate the prognostic performance of t...

[5 rows x 29 columns]

=== conditions_studies ===
   id  nct_id  condition_id       date
0   0      11           285 2000-01-01
1   1      29           572 2000-01-01
2   2      29          1021 2000-01-01
3   3      11           114 2000-01-01
4   4      11           401 2000-01-01

=== interventions ===
   intervention_id    mesh_term
0                0    Tepotinib
1                1    Sirolimus
2                2     Nicotine
3                3  Carboplatin
4                4  Amoxicillin

In [42]:
table_names

['outcomes',
 'interventions_studies',
 'drop_withdrawals',
 'sponsors',
 'outcome_analyses',
 'designs',
 'facilities_studies',
 'eligibilities',
 'conditions',
 'sponsors_studies',
 'reported_event_totals',
 'facilities',
 'studies',
 'conditions_studies',
 'interventions']

## Outcomes

In [18]:
db.table_dict["outcomes"].df.set_index("id").head()

,nct_id,outcome_type,title,description,time_frame,population,units,units_analyzed,dispersion_type,param_type,date
id,,,,,,,,,,,
0,332,Secondary,Mean Change From Baseline in Nighttime Symptom...,Mean change from baseline in Nighttime Symptom...,Baseline and Week 2,The secondary efficacy analyses were based on ...,Units on a Scale,NaN,95% Confidence Interval,Least Squares Mean,2000-05-31
1,332,Secondary,Mean Change From Baseline in Rhinoconjunctivit...,"Patients completed the validated, self-adminis...",Week 2,This secondary endpoint analysis was performed...,Units on a Scale,NaN,95% Confidence Interval,Least Squares Mean,2000-05-31
2,332,Secondary,Mean Change From Baseline in Daytime Eye Sympt...,Mean change from baseline in Daytime Eye Sympt...,Baseline and Week 2,The secondary efficacy analyses were based on ...,Units on a Scale,NaN,95% Confidence Interval,Least Squares Mean,2000-05-31
3,332,Secondary,Patient's Global Evaluation of Allergic Rhinit...,"An evaluation by the patient, administered at ...",Week 2,This secondary endpoint analysis was performed...,Units on a Scale,NaN,95% Confidence Interval,Least Squares Mean,2000-05-31
4,332,Secondary,Physician's Global Evaluation of Allergic Rhin...,"An evaluation by the physician, administered a...",Week 2,This secondary endpoint analysis was performed...,Units on a Scale,NaN,95% Confidence Interval,Least Squares Mean,2000-05-31

In [21]:
print(len(db.table_dict["outcomes"].df))
db.table_dict["outcomes"].df.set_index("id").nunique()

411933

nct_id              52941
outcome_type            4
title              340156
description        311350
time_frame         117762
population         125182
units               32452
units_analyzed       1624
dispersion_type        35
param_type              9
date                 3755
dtype: int64

In [25]:
db.table_dict["outcomes"].df.groupby("param_type").count()

,id,nct_id,outcome_type,title,description,time_frame,population,units,units_analyzed,dispersion_type,date
param_type,,,,,,,,,,,
Count of Participants,50101,50101,50101,50101,47039,50101,34943,50101,0,0,50101
Count of Units,919,919,919,919,882,919,673,919,919,0,919
Geometric Least Squares Mean,357,357,357,357,354,357,314,357,0,357,357
Geometric Mean,20130,20130,20130,20130,17512,20130,19180,20130,44,20130,20130
Least Squares Mean,25713,25713,25713,25713,24331,25713,23890,25711,165,25710,25713
Log Mean,81,81,81,81,80,81,37,81,8,81,81
Mean,149598,149598,149598,149598,138270,149597,109787,149589,3177,149595,149598
Median,34812,34812,34812,34812,31585,34812,26054,34806,341,34811,34812
Number,104145,104145,104145,104145,96223,104144,85319,104123,3285,20266,104145

In [28]:
db.table_dict["outcomes"].df.groupby("dispersion_type").count().sort_values("id", ascending=False)

,id,nct_id,outcome_type,title,description,time_frame,population,units,units_analyzed,param_type,date
dispersion_type,,,,,,,,,,,
Standard Deviation,127605,127605,127605,127605,117482,127605,96097,127596,2732,127605,127605
95% Confidence Interval,50155,50155,50155,50155,47668,50155,42142,50149,867,50155,50155
Standard Error,31903,31903,31903,31903,30117,31903,26561,31901,295,31903,31903
Full Range,15466,15466,15466,15466,13524,15465,11856,15466,200,15466,15466
Inter-Quartile Range,11667,11667,11667,11667,10516,11667,7024,11666,165,11667,11667
Geometric Coefficient of Variation,10897,10897,10897,10897,9037,10897,10530,10897,23,10897,10897
90% Confidence Interval,2630,2630,2630,2630,2508,2630,2334,2629,42,2630,2630
80% Confidence Interval,368,368,368,368,354,368,339,368,2,368,368
97.5% Confidence Interval,102,102,102,102,100,102,91,102,1,102,102
99% Confidence Interval,63,63,63,63,61,63,45,63,0,63,63
98.3% Confidence Interval,25,25,25,25,25,25,25,25,0,25,25
60% Confidence Interval,12,12,12,12,12,12,12,12,0,12,12
99.4% Confidence Interval,8,8,8,8,8,8,0,8,0,8,8
99.8% Confidence Interval,7,7,7,7,7,7,6,7,0,7,7
95.1% Confidence Interval,7,7,7,7,7,7,7,7,0,7,7
96% Confidence Interval,6,6,6,6,6,6,6,6,2,6,6
98.75% Confidence Interval,4,4,4,4,4,4,4,4,0,4,4
1% Confidence Interval,3,3,3,3,3,3,3,3,3,3,3
98% Confidence Interval,3,3,3,3,3,3,3,3,0,3,3
70% Confidence Interval,2,2,2,2,2,2,2,2,0,2,2
97.18% Confidence Interval,2,2,2,2,2,2,2,2,0,2,2
99.87% Confidence Interval,2,2,2,2,2,2,2,2,2,2,2
2.5% Confidence Interval,1,1,1,1,1,1,1,1,0,1,1
25% Confidence Interval,1,1,1,1,1,1,1,1,0,1,1
5% Confidence Interval,1,1,1,1,1,1,1,1,0,1,1
68% Confidence Interval,1,1,1,1,1,1,1,1,0,1,1
99.9% Confidence Interval,1,1,1,1,1,1,1,1,0,1,1
94% Confidence Interval,1,1,1,1,1,1,1,1,0,1,1
75% Confidence Interval,1,1,1,1,1,1,0,1,0,1,1
100% Confidence Interval,1,1,1,1,1,1,0,1,0,1,1
98.66% Confidence Interval,1,1,1,1,1,1,1,1,0,1,1
98.33% Confidence Interval,1,1,1,1,1,1,1,1,0,1,1
87% Confidence Interval,1,1,1,1,1,1,1,1,0,1,1
91.8% Confidence Interval,1,1,1,1,1,1,1,1,0,1,1
85% Confidence Interval,1,1,1,1,1,1,0,1,0,1,1

In [31]:
db.table_dict["outcomes"].df.groupby("outcome_type").count().sort_values("id", ascending=False)

,id,nct_id,title,description,time_frame,population,units,units_analyzed,dispersion_type,param_type,date
outcome_type,,,,,,,,,,,
Secondary,280628,280628,280628,255021,280584,224097,262219,4456,174166,262246,280628
Primary,115152,115152,115152,106294,115139,83770,110549,3107,68971,110555,115152
Other Pre-specified,14728,14728,14728,13184,14726,9409,11643,408,7025,11643,14728
Post-Hoc,1425,1425,1425,1300,1425,1076,1412,19,788,1412,1425

In [34]:
outcomes_df = db.table_dict["outcomes"].df.copy()

str_cols = outcomes_df.select_dtypes(include=["object", "string"]).columns
outcomes_df[str_cols] = outcomes_df[str_cols].apply(
    lambda s: s.str.lower().str.replace("_", " ", regex=False).str.replace("-", " ", regex=False)
)

outcomes_df.groupby("units").count().sort_values("id", ascending=False)

,id,nct_id,outcome_type,title,description,time_frame,population,units_analyzed,dispersion_type,param_type,date
units,,,,,,,,,,,
participants,86175,86175,86175,86175,79742,86175,62833,122,254,86174,86175
percentage of participants,36780,36780,36780,36780,34173,36780,33389,126,12831,36780,36780
units on a scale,34768,34768,34768,34768,34717,34768,25838,553,34582,34768,34768
score on a scale,16744,16744,16744,16744,16740,16744,11784,208,16637,16744,16744
months,8703,8703,8703,8703,8344,8703,6875,25,8595,8703,8703
...,...,...,...,...,...,...,...,...,...,...,...
number of sentinel nodes per patient,1,1,1,1,1,1,0,0,1,1,1
number of sensors,1,1,1,1,1,1,1,0,1,1,1
number of sensor used per month,1,1,1,1,1,1,1,0,1,1,1
number of sensor changes,1,1,1,1,1,1,1,0,0,1,1
percentage exergaming sessions attended,1,1,1,1,1,1,1,0,1,1,1

In [35]:
outcomes_df = db.table_dict["outcomes"].df.copy()

str_cols = outcomes_df.select_dtypes(include=["object", "string"]).columns
outcomes_df[str_cols] = outcomes_df[str_cols].apply(
    lambda s: s.str.lower().str.replace("_", " ", regex=False).str.replace("-", " ", regex=False)
)

outcomes_df.groupby("units_analyzed").count().sort_values("id", ascending=False)

,id,nct_id,outcome_type,title,description,time_frame,population,units,dispersion_type,param_type,date
units_analyzed,,,,,,,,,,,
eyes,1838,1838,1838,1838,1769,1838,1316,1838,1128,1838,1838
lesions,320,320,320,320,312,320,250,315,162,315,320
target lesions,203,203,203,203,103,203,199,203,164,203,203
limbs,176,176,176,176,176,176,152,176,94,176,176
implants,123,123,123,123,112,123,93,123,67,123,123
...,...,...,...,...,...,...,...,...,...,...,...
moderate or severe copd exacerbations,1,1,1,1,1,1,1,1,1,1,1
molar teeth,1,1,1,1,1,1,0,1,0,1,1
monitored study visits,1,1,1,1,1,1,1,1,0,1,1
months when dry weight adjustment happen,1,1,1,1,1,1,0,1,0,1,1
zuhlke adhesion score,1,1,1,1,1,1,0,1,1,1,1

In [36]:
outcomes_df = db.table_dict["outcomes"].df.copy()

str_cols = outcomes_df.select_dtypes(include=["object", "string"]).columns
outcomes_df[str_cols] = outcomes_df[str_cols].apply(
    lambda s: s.str.lower().str.replace("_", " ", regex=False).str.replace("-", " ", regex=False)
)

outcomes_df.groupby("time_frame").count().sort_values("id", ascending=False)

,id,nct_id,outcome_type,title,description,population,units,units_analyzed,dispersion_type,param_type,date
time_frame,,,,,,,,,,,
6 months,4773,4773,4773,4773,4234,2605,4244,93,2365,4244,4773
12 months,3993,3993,3993,3993,3494,2380,3635,123,1793,3635,3993
baseline,3454,3454,3454,3454,3136,1986,3254,106,2348,3254,3454
12 weeks,3256,3256,3256,3256,2785,1889,2955,28,1951,2956,3256
1 year,2493,2493,2493,2493,2069,1366,2110,132,902,2111,2493
...,...,...,...,...,...,...,...,...,...,...,...
"days: 1, 2 4, weeks 1 to 4, week 8, 12 and month 6, then every 3 months thereafter until progression then during ltfu",1,1,1,1,1,1,1,0,1,1,1
"days: 1, 15",1,1,1,1,1,1,1,0,1,1,1
days1 through 6,1,1,1,1,1,0,1,0,0,1,1
days to full epithelialization,1,1,1,1,1,1,1,0,1,1,1
"from date of randomization until the date of study withdrawal or sub study completion at 6 months, whichever came first.",1,1,1,1,1,0,1,0,0,1,1

In [38]:
outcomes_df = db.table_dict["outcomes"].df.copy()

str_cols = outcomes_df.select_dtypes(include=["object", "string"]).columns
outcomes_df[str_cols] = outcomes_df[str_cols].apply(
    lambda s: s.str.lower().str.replace("_", " ", regex=False).str.replace("-", " ", regex=False)
)

outcomes_df.groupby("title").count().sort_values("id", ascending=False)

,id,nct_id,outcome_type,description,time_frame,population,units,units_analyzed,dispersion_type,param_type,date
title,,,,,,,,,,,
overall survival,1610,1610,1610,1425,1607,999,1421,2,1178,1421,1610
progression free survival (pfs),1087,1087,1087,1066,1086,863,991,4,937,991,1087
progression free survival,1013,1013,1013,938,1010,630,889,2,810,889,1013
overall survival (os),1012,1012,1012,980,1011,808,943,7,858,943,1012
number of participants with adverse events,554,554,554,504,554,322,546,0,1,546,554
...,...,...,...,...,...,...,...,...,...,...,...
"fabrication efficacy tissue adaptation, palatal rim. number of participants with poor adaptation",1,1,1,1,1,0,1,0,0,1,1
"fabrication efficacy tissue adaptation, number of subjects whose splints had excessive material",1,1,1,1,1,0,1,0,0,1,1
"fabrication efficacy tissue adaptation, facial rim. number of participants with poor adaptation",1,1,1,1,1,0,1,0,0,1,1
"fabrication efficacy retention trials, month 4",1,1,1,1,1,1,1,0,1,1,1
△ot value,1,1,1,1,1,1,1,0,1,1,1

In [37]:
outcomes_df = db.table_dict["outcomes"].df.copy()

str_cols = outcomes_df.select_dtypes(include=["object", "string"]).columns
outcomes_df[str_cols] = outcomes_df[str_cols].apply(
    lambda s: s.str.lower().str.replace("_", " ", regex=False).str.replace("-", " ", regex=False)
)

outcomes_df.groupby("description").count().sort_values("id", ascending=False)

,id,nct_id,outcome_type,title,time_frame,population,units,units_analyzed,dispersion_type,param_type,date
description,,,,,,,,,,,
"serious adverse events (saes) assessed include medical occurrences that result in death, are life threatening, require hospitalization or prolongation of hospitalization or result in disability/incapacity.",139,139,139,139,139,133,139,0,1,139,139
blood samples were collected at specified time points for gsk2831781 in plasma.,93,93,93,93,93,93,35,0,35,35,93
"an unsolicited ae covers any untoward medical occurrence in a clinical investigation subject temporally associated with the use of a medicinal product, whether or not considered related to the medicinal product and reported in addition to those solicited during the clinical study and any solicited symptom with onset outside the specified period of follow up for solicited symptoms. any was defined as the occurrence of any unsolicited ae regardless of intensity grade or relation to vaccination.",90,90,90,90,90,89,90,0,0,90,90
bioequivalence based on cmax,87,87,87,87,87,86,87,0,87,87,87
bioequivalence based on auc0 t,80,80,80,80,80,79,80,0,80,80,80
...,...,...,...,...,...,...,...,...,...,...,...
hypothesis 2b: metformin will improve cardiac function in type 1 diabetes by echocardiogram.~mitral valve e/a ratio is the ratio of early (e) to late (a) ventricular filling velocities.~ideal myocardial tissue relaxation is indicated by a ratio of >0.8 and <2.0.,1,1,1,1,1,1,1,0,1,1,1
"hypothesis is that anicgm device will perform similarly as other blood glucose monitoring devices mean absolute relative difference (mard) is computed by taking the arithmetic mean of the absolute relative differences between the anicgm system measures and the reference standard fs bg, which serves as the denominator of the calculation. the mard is expressed as a percentage, and a lower mard signifies better concordance between the two measurements.",1,1,1,1,1,0,1,0,1,1,1
"hypothesis: 85% of eyes will have uncorrected visual acuity of 20/40 or better, as measured using etdrs logmar charts at 4 meters",1,1,1,1,1,0,1,1,0,1,1
"hypothesis: <5% of eyes will have a loss of > 2 lines of bscva at any postoperative visit, as measured using etdrs logmar visual acuity charts at 4 meters",1,1,1,1,1,0,1,1,0,1,1
"① stand up from the chair without support. ② walk 3m from chair. ③ turn around. ④ sit back in the chair. measure the time(second), higher values represent a worse outcome. lower values represent a better outcome.",1,1,1,1,1,0,1,0,1,1,1

## Interventions Studies

In [43]:
print(len(db.table_dict["interventions_studies"].df))
db.table_dict["interventions_studies"].df.set_index("id").nunique()

171771

nct_id             90364
intervention_id     3432
date                5041
dtype: int64

In [44]:
db.table_dict["interventions_studies"].df.head()

   id  nct_id  intervention_id       date
0   0      25             1619 2000-01-01
1   1      22              439 2000-01-01
2   2      15             1115 2000-01-01
3   3      17             2099 2000-01-01
4   4      15             1114 2000-01-01

## Drop Withdrawals

In [45]:
print(len(db.table_dict["drop_withdrawals"].df))
db.table_dict["drop_withdrawals"].df.set_index("id").nunique()

381199

nct_id    32129
period     7039
reason    22089
count       919
date       3406
dtype: int64

In [46]:
db.table_dict["drop_withdrawals"].df.set_index("id").head()

    nct_id         period            reason  count       date
id
0      332  Overall Study  Lack of Efficacy    8.0 2000-05-31
1      332  Overall Study      out-of-state    1.0 2000-05-31
2      332  Overall Study     Noncompliance    0.0 2000-05-31
3      332  Overall Study     Noncompliance    0.0 2000-05-31
4      332  Overall Study     Noncompliance    0.0 2000-05-31

In [47]:
outcomes_df = db.table_dict["drop_withdrawals"].df.copy()

str_cols = outcomes_df.select_dtypes(include=["object", "string"]).columns
outcomes_df[str_cols] = outcomes_df[str_cols].apply(
    lambda s: s.str.lower().str.replace("_", " ", regex=False).str.replace("-", " ", regex=False)
)

outcomes_df.groupby("period").count().sort_values("id", ascending=False)

,id,nct_id,reason,count,date
period,,,,,
overall study,235590,235590,235590,235586,235590
treatment period,3193,3193,3193,3193,3193
period 1,2375,2375,2375,2375,2375
period 2,1775,1775,1775,1775,1775
double blind phase,1262,1262,1262,1262,1262
...,...,...,...,...,...
disease progression after trtmt: onstudy,1,1,1,1,1
pet imaging and assessment,1,1,1,1,1
period1bevacizumab & irinotecan patients,1,1,1,1,1
treatment phase 1 (5 months),1,1,1,1,1
zanubrutinib + rifabutin on day 11,1,1,1,1,1

In [48]:
outcomes_df = db.table_dict["drop_withdrawals"].df.copy()

str_cols = outcomes_df.select_dtypes(include=["object", "string"]).columns
outcomes_df[str_cols] = outcomes_df[str_cols].apply(
    lambda s: s.str.lower().str.replace("_", " ", regex=False).str.replace("-", " ", regex=False)
)

outcomes_df.groupby("reason").count().sort_values("id", ascending=False)

,id,nct_id,period,count,date
reason,,,,,
withdrawal by subject,60029,60029,60029,60028,60029
adverse event,49646,49646,49646,49646,49646
lost to follow up,46796,46796,46796,46795,46796
protocol violation,22505,22505,22505,22504,22505
death,20243,20243,20243,20243,20243
...,...,...,...,...,...
study ended by sponsor once primary/ secondary analysis was complete and participants discontinued,1,1,1,1,1
due to participant's health fund,1,1,1,1,1
patients with no her2 abnormality,1,1,1,1,1
patients without circulating tumor cells,1,1,1,1,1
other transitioned to 9785 cl 0123,1,1,1,1,1

In [ ]:
outcomes_df = db.table_dict["drop_withdrawals"].df.copy()

outcomes_df.groupby("count").count().sort_values("id", ascending=False)

                id  nct_id  period  reason    date
count
0.0         153924  153924  153924  153924  153924
1.0          83500   83500   83500   83500   83500
2.0          36296   36296   36296   36296   36296
3.0          21621   21621   21621   21621   21621
4.0          14167   14167   14167   14167   14167
...            ...     ...     ...     ...     ...
767.0            1       1       1       1       1
759.0            1       1       1       1       1
758.0            1       1       1       1       1
757.0            1       1       1       1       1
11655523.0       1       1       1       1       1

[919 rows x 5 columns]

In [50]:
outcomes_df = db.table_dict["drop_withdrawals"].df.copy()

outcomes_df.describe()

                 id        nct_id         count                           date
count      381199.0      381199.0  3.811950e+05                         381199
mean       190599.0  95615.302362  4.211414e+01  2014-08-04 01:09:19.767470848
min             0.0          38.0  0.000000e+00            2000-05-31 00:00:00
25%         95299.5       45773.0  0.000000e+00            2011-04-30 00:00:00
50%        190599.0       88516.0  1.000000e+00            2014-10-31 00:00:00
75%        285898.5      140807.0  3.000000e+00            2018-01-22 00:00:00
max        381198.0      246529.0  1.165552e+07            2021-01-01 00:00:00
std    110042.81697   58498.71249  1.889499e+04                            NaN

## Sponsors

In [52]:
print(len(db.table_dict["sponsors"].df))
db.table_dict["sponsors"].df.nunique()

53241

sponsor_id      53241
name            53241
agency_class        9
dtype: int64

In [53]:
db.table_dict["sponsors"].df.head()

   sponsor_id                                    name agency_class
0           0   Johns Hopkins All Children's Hospital        OTHER
1           1            Florida Department of Health    OTHER_GOV
2           2                      NYU Langone Health        OTHER
3           3  Wake Forest University Health Sciences        OTHER
4           4                         Gilead Sciences     INDUSTRY

In [55]:
outcomes_df = db.table_dict["sponsors"].df.copy()

str_cols = outcomes_df.select_dtypes(include=["object", "string"]).columns
outcomes_df[str_cols] = outcomes_df[str_cols].apply(
    lambda s: s.str.lower().str.replace("_", " ", regex=False).str.replace("-", " ", regex=False)
)

outcomes_df.groupby("agency_class").count()

              sponsor_id   name
agency_class
ambig                 22     22
fed                  258    258
indiv                264    264
industry           10761  10761
network              391    391
nih                   44     44
other              21528  21528
other gov           1275   1275
unknown            18698  18698

In [60]:
outcomes_df = db.table_dict["sponsors"].df.copy()

str_cols = outcomes_df.select_dtypes(include=["object", "string"]).columns
outcomes_df[str_cols] = outcomes_df[str_cols].apply(
    lambda s: s.str.lower().str.replace("_", " ", regex=False).str.replace("-", " ", regex=False)
)

outcomes_df.groupby("name").count()

                               sponsor_id  agency_class
name
01 expert systems, llc                  1             1
1 million 4 anna foundation             1             1
101 therapeutics                        1             1
10xbio, llc                             1             1
113 suicide prevention                  1             1
...                                   ...           ...
şeyda öztürk                            1             1
şeyhmus kaplan                          1             1
şeyma demiralay                         1             1
šarić, jadranka pavičić, m.d.           1             1
żelazna medical centre, llc             1             1

[53237 rows x 2 columns]

## Outcome Analyses

In [62]:
db.table_dict["outcome_analyses"].df.set_index("id").head()

,nct_id,outcome_id,non_inferiority_type,non_inferiority_description,param_type,param_value,dispersion_type,dispersion_value,p_value_modifier,p_value,...,p_value_description,method,method_description,estimate_description,groups_description,other_analysis_description,ci_upper_limit_raw,ci_lower_limit_raw,p_value_raw,date
id,,,,,,,,,,,,,,,,,,,,,
0,646,7,Non-Inferiority or Equivalence,ANOVA will be performed on ln-transformed Ae0-...,Ratio of the mean,97.94,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Bioequivalence is established when 90% Confide...,NaN,NaN,NaN,NaN,NaN,2000-07-31
1,646,6,Non-Inferiority or Equivalence,ANOVA will be performed on ln-transformed Ae0-...,Ratio of the mean,100.36,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,Bioequivalence is established when 90% Confide...,NaN,NaN,NaN,NaN,NaN,2000-07-31
2,757,12,Superiority or Other,NaN,NaN,NaN,NaN,NaN,<,0.0001,...,NaN,"t-test, 2 sided",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-09-30
3,757,10,Superiority or Other,NaN,NaN,NaN,NaN,NaN,<,0.0001,...,NaN,"t-test, 2 sided",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-09-30
4,757,11,Superiority or Other,NaN,NaN,NaN,NaN,NaN,<,0.0001,...,NaN,"t-test, 2 sided",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-09-30

In [66]:
outcomes_df = db.table_dict["outcome_analyses"].df.copy()

str_cols = outcomes_df.select_dtypes(include=["object", "string"]).columns
outcomes_df[str_cols] = outcomes_df[str_cols].apply(
    lambda s: s.str.lower().str.replace("_", " ", regex=False).str.replace("-", " ", regex=False)
)

outcomes_df.set_index("id").nunique().sort_values(ascending=False)

outcome_id                     92853
groups_description             59637
ci_upper_limit                 23627
ci_lower_limit                 22367
param_value                    21733
nct_id                         18222
p_value_description            15428
estimate_description           12902
p_value                        11088
method_description             10181
non_inferiority_description     9221
dispersion_value                9082
param_type                      3942
date                            2784
method                          2550
other_analysis_description       916
ci_percent                       145
ci_upper_limit_na_comment         18
p_value_modifier                  10
non_inferiority_type               8
ci_n_sides                         2
dispersion_type                    2
ci_upper_limit_raw                 0
ci_lower_limit_raw                 0
p_value_raw                        0
dtype: int64

In [69]:
outcomes_df.ci_n_sides.unique()

array([nan, '2 sided', '1 sided'], dtype=object)

In [70]:
outcomes_df.dispersion_type.unique()

array([nan, 'standard deviation', 'standard error of the mean'],
      dtype=object)

In [71]:
outcomes_df.non_inferiority_type.unique()

array(['non inferiority or equivalence', 'superiority or other',
       'non inferiority or equivalence (legacy)',
       'superiority or other (legacy)', 'other', 'superiority',
       'non inferiority', 'equivalence'], dtype=object)

In [73]:
outcomes_df.groupby("method").count().sort_values("id",ascending=False)

,id,nct_id,outcome_id,non_inferiority_type,non_inferiority_description,param_type,param_value,dispersion_type,dispersion_value,p_value_modifier,...,ci_upper_limit_na_comment,p_value_description,method_description,estimate_description,groups_description,other_analysis_description,ci_upper_limit_raw,ci_lower_limit_raw,p_value_raw,date
method,,,,,,,,,,,,,,,,,,,,,
ancova,35969,35969,35969,35969,2686,27868,27866,11950,11950,8772,...,0,13887,10559,5294,22346,68,0,0,0,35969
mixed models analysis,24789,24789,24789,24789,1840,19780,19769,8828,8828,6023,...,0,8125,6587,4660,14820,118,0,0,0,24789
anova,15725,15725,15725,15725,2581,9138,9137,2703,2703,4040,...,0,4623,4534,2761,10711,120,0,0,0,15725
"t test, 2 sided",14032,14032,14032,14032,1422,4856,4854,1713,1713,3263,...,0,3508,2016,885,7324,121,0,0,0,14032
"regression, logistic",10386,10386,10386,10386,488,9017,9013,251,251,1995,...,3,5047,2177,2264,7167,61,0,0,0,10386
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
qualitative comparison,1,1,1,1,0,1,1,1,1,0,...,0,0,1,0,0,0,0,0,0,1
cohen f,1,1,1,1,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
quantile regression models,1,1,1,1,0,1,1,1,1,0,...,0,0,1,1,1,0,0,0,0,1
quasi likelihood nb* regression,1,1,1,1,0,1,1,0,0,1,...,0,0,1,0,0,0,0,0,0,1
percent,1,1,1,1,0,1,1,0,0,1,...,0,0,0,1,0,0,0,0,0,1

In [74]:
outcomes_df.groupby("p_value").count().sort_values("id",ascending=False)

,id,nct_id,outcome_id,non_inferiority_type,non_inferiority_description,param_type,param_value,dispersion_type,dispersion_value,p_value_modifier,...,p_value_description,method,method_description,estimate_description,groups_description,other_analysis_description,ci_upper_limit_raw,ci_lower_limit_raw,p_value_raw,date
p_value,,,,,,,,,,,,,,,,,,,,,
0.001000,21612,21612,21612,21612,1542,14710,14706,4570,4570,19841,...,9016,21612,5850,2769,11506,145,0,0,0,21612
0.000100,16460,16460,16460,16460,1172,11496,11493,3968,3968,15592,...,6328,16460,4332,3342,10473,85,0,0,0,16460
0.050000,5006,5006,5006,5006,800,1455,1452,450,450,3943,...,1210,5006,769,343,2552,71,0,0,0,5006
1.000000,2209,2209,2209,2209,222,893,893,98,98,42,...,810,2209,251,472,1326,5,0,0,0,2209
0.010000,2061,2061,2061,2061,178,892,891,193,193,1022,...,712,2061,377,285,1119,17,0,0,0,2061
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0.598141,1,1,1,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
0.599171,1,1,1,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
0.600200,1,1,1,1,0,1,1,0,0,0,...,0,1,0,0,1,0,0,0,0,1
0.601716,1,1,1,1,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,1
3152.000000,1,1,1,1,1,0,0,0,0,1,...,1,1,1,0,1,0,0,0,0,1

In [75]:
outcomes_df.groupby("groups_description").count().sort_values("id",ascending=False)

,id,nct_id,outcome_id,non_inferiority_type,non_inferiority_description,param_type,param_value,dispersion_type,dispersion_value,p_value_modifier,...,ci_upper_limit_na_comment,p_value_description,method,method_description,estimate_description,other_analysis_description,ci_upper_limit_raw,ci_lower_limit_raw,p_value_raw,date
groups_description,,,,,,,,,,,,,,,,,,,,,
week 12,822,822,822,822,46,592,592,185,185,127,...,0,440,779,133,126,3,0,0,0,822
week 4,715,715,715,715,49,615,615,214,214,133,...,0,355,685,141,161,0,0,0,0,715
week 8,611,611,611,611,46,534,534,157,157,102,...,0,340,592,116,86,0,0,0,0,611
week 2,532,532,532,532,20,417,417,167,167,66,...,0,309,521,82,71,0,0,0,0,532
week 24,484,484,484,484,19,309,309,110,110,95,...,0,177,449,122,138,1,0,0,0,484
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"hui comprehensive health state attribute, at 12 months with the osia system vs unaided at visit 1.",1,1,1,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
"hui dexterity attribute, at 12 months with the osia system vs unaided at visit 1.",1,1,1,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
"hui dexterity attribute, at 3 months with the osia system vs unaided at visit 1.",1,1,1,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
"hui emotion attribute, at 12 months with the osia system vs unaided at visit 1.",1,1,1,1,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
≥90% reduction,1,1,1,1,1,1,1,0,0,1,...,0,1,1,1,1,0,0,0,0,1

In [78]:
outcomes_df.other_analysis_description.dropna(inplace=False).value_counts()

other_analysis_description
gmc ratio and 95% ci were estimated from a clda model.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   60
the ratio is calculated as the gmc of the boostrix group divided by the gmc of the td group.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             50
gmt ratio and 95% ci were estimated from a clda model.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   45
pr5i minus infanrix™ hexa                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                37
treatment difference = standard tf cbt   stepped care tf cbt                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             25
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ..
the effect size used is the adjusted cohen's d, calculated from the coefficient for treatment group in the mixed model, divided by total pooled sd (the square root of the sum of the residual variance+the variance of the group level random effects).                                                                                                                                                                                                                                                                                                                                                                                                  1
we compared the change in gas scores when using an arm support device on three goal areas identified as important for each participant. for each goal, we measured abilities at baseline and with the device (kinova and wrex). we calculated the change in score for each goal and averaged these change scores across all participants. while our groups are too small to complete statistical tests to estimate the significance of the differences participants noted in activity and independence while using both arm supports, our results quantify the amount of increased success participants noted with the use of the arm support device.     1
counts from each axis (x, y, z) were measured across baseline and during the 4 week trial to explore arm movement and positioning during the use of an upper extremity arm device. counts (within each participant) were summed. a change score from trial minus baseline was calculated for each axis. we provide an average change score and standard deviation across participants with kinova and participants with wrex.                                                                                                                                                                                                                             1
a single group analysis was used to determine this outcome measure. these are basic science, hypothesis generating studies with limited numbers of participants and no control group. the outcomes have no comparisons built into them   the outcomes are stating what the cell counts are, what the antibody titers are, what percentage of people seroconverted, etc. as such, we cannot report any p values etc. for comparisons (e.g. with unvaccinated people                                                                                                                                                                                        1
due to the small sample size, we utilized change in activity count data when comparing two upper limb testing sessions: one without the use of an arm support device (kinova or wrex) and one while using the arm support device. for each upper extremity task, we summed all activity count data for all tasks completed. we then computed means and standard deviations. data presented are within group data change and not between group data comparisons.                                                                                                                                                                                           1
Name: count, Length: 916, dtype: int64

## Designs

In [79]:
db.table_dict["designs"].df.set_index("id").head()

,nct_id,allocation,intervention_model,observational_model,primary_purpose,time_perspective,masking,masking_description,intervention_model_description,subject_masked,caregiver_masked,investigator_masked,outcomes_assessor_masked,date
id,,,,,,,,,,,,,,
0,5,NaN,NaN,Cohort,NaN,Retrospective,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-01-01
1,0,NaN,NaN,Cohort,NaN,Retrospective,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-01-01
2,10,NaN,NaN,Cohort,NaN,Retrospective,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-01-01
3,18,NaN,NaN,Cohort,NaN,Retrospective,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-01-01
4,11,NaN,NaN,Cohort,NaN,Retrospective,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000-01-01

In [83]:
db.table_dict["designs"].df.set_index("id").count()

nct_id                            249093
allocation                        155937
intervention_model                198024
observational_model                47428
primary_purpose                   194280
time_perspective                   49179
masking                           198329
masking_description                11390
intervention_model_description     21510
subject_masked                     68466
caregiver_masked                   32030
investigator_masked                56101
outcomes_assessor_masked           47705
date                              249093
dtype: int64

## Facilities Studies

## Eligibilities

## Conditions

## Sponsors Studies

## Reported Event Totals

## Facilities

## Studies

## Conditions Studies

## Interventions